# initial starting values for each chain
my_inits <- function(chain){
  gen_list <- function(chain = chain){
    list(
      x = matrix(1,
                 ncol = data_list$nseason,
                 nrow = data_list$nsite),
      p0_mu = rnorm(data_list$nspec),
      p0_tau = rgamma(data_list$nspec,1,1),
      p0 = matrix(1,
                  ncol = data_list$ncity,
                  nrow = data_list$nspec), 
      p1_mu = rnorm(data_list$nspec),
      p1_tau = rgamma(data_list$nspec,1,1),
      p1 = matrix(1,
                  ncol = data_list$ncity,
                  nrow = data_list$nspec), 
      phi_mu = rnorm(data_list$nspec),
      phi_tau = rgamma(data_list$nspec,1,1),
      phi = matrix(1,
                   ncol = data_list$ncity,
                   nrow = data_list$nspec), 
      a0_mu = rnorm(1),
      a0_tau = rgamma(1,1,1),
      a0 = rnorm(data_list$ncity),
      a1_mu = rnorm(1),
      a1_tau = rgamma(1,1,1),
      a1 = rnorm(data_list$ncity),
      b0_mu = rnorm(1),
      b0_tau = rgamma(1,1,1),
      b0 = rnorm(data_list$ncity),
      b1_mu = rnorm(1),
      b1_tau = rgamma(1,1,1),
      b1 = rnorm(data_list$ncity),
      c0_mu = rnorm(1),
      c0_tau = rgamma(1,1,1),
      c0 = rnorm(data_list$ncity),
      c1_mu = rnorm(1),
      c1_tau = rgamma(1,1,1),
      c1 = rnorm(data_list$ncity),
      d0_mu = rnorm(1),
      d0_tau = rgamma(1,1,1),
      d0 = rnorm(data_list$ncity), 
      d1_mu = rnorm(1),
      d1_tau = rgamma(1,1,1),
      d1 = rnorm(data_list$ncity),
      e0_mu = rnorm(1),
      e0_tau = rgamma(1,1,1),
      e0 = rnorm(data_list$ncity), 
      e1_mu = rnorm(1),
      e1_tau = rgamma(1,1,1),
      e1 = rnorm(data_list$ncity), 
      g0_mu = rnorm(1),
      g0_tau = rgamma(1,1,1),
      g0 = rnorm(data_list$ncity), 
      g1_mu = rnorm(1),
      g1_tau = rgamma(1,1,1),
      g1 = rnorm(data_list$ncity)
    )
  }
  return(
    switch(
      chain,
      "1" = gen_list(chain),
      "2" = gen_list(chain),
      "3" = gen_list(chain),
      "4" = gen_list(chain),
      "5" = gen_list(chain),
      "6" = gen_list(chain),
      "7" = gen_list(chain),
      "8" = gen_list(chain)
    )
  )
}